"""empty message

Revision ID: 1f176528d6d5
Revises: 947a06d8306a
Create Date: 2021-05-11 11:07:32.882645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f176528d6d5'
down_revision = '947a06d8306a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Numeric(precision=4), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('seats', sa.Numeric(precision=2), nullable=True),
    sa.Column('horsepower', sa.Numeric(precision=4), nullable=True),
    sa.Column('torque', sa.Numeric(precision=3), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('interior', sa.String(length=20), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
